
nx: 4
nu: 1

# cost
Q:
  q1: 1
  q2: 1
  q3: 0.1
  q4: 0.1
Qn:
  q1: 500
  q2: 500
  q3: 100
  q4: 100
R:
  r1: 0.01

# dynamics
m_cart: 1
m_pole: 0.1
l: 1

# initial state
initial_state:
  pos: 0
  theta: -3.1416
  vel: 0
  omega: 0

# mpc settings
dt: 0.005
horizon: 100
mpcFrequency: 500
mrtFrequency: 500
useFeedbackPolicy: false

# line search
sigma: 0.5
beta: 1.0e-2

# iLQR convergence
max_iteration: 10
tolerance: 1.0e-2

# verbose
verbose_cal_time: true