
nx: 4
nu: 1

# cost
Q:
  q1: 100
  q2: 100
  q3: 10
  q4: 10
Qn:
  q1: 500
  q2: 500
  q3: 100
  q4: 100
R:
  r1: 1

# dynamics
m_cart: 1
m_pole: 0.1
l: 1

# initial state
initial_state:
  pos: 0
  theta: -3.1416
  vel: 0
  omega: 0

use_which_solver: 2   # 1 for iLQR, 2 for dms

K: [0, 0, 0, 0]

# mpc settings
dt: 0.005
horizon: 100
mpcFrequency: 500
mrtFrequency: 500
useFeedbackPolicy: false

# iLQR settings
iLQR:
  # line search
  sigma: 0.5
  beta: 1.0e-2

  # iLQR convergence
  max_iteration: 100
  tolerance: 1.0e-2

  # verbose
  verbose_cal_time: true

dms:
  # dms convergence
  max_iteration: 100
  tolerance: 1.0e-2

  # verbose
  verbose_cal_time: true