
nx: 36
nu: 12
nq: 18
nv: 18

# simulator initial state
initial_state : [-0.1, 1.1, -2.6,
                  0.1, 1.1, -2.6,
                 -0.1, 1.1, -2.6,
                  0.1, 1.1, -2.6]

# solver initial state
q_init : [ 0.0, 0.0, 0.3,        # base position
           0.0, 0.0, 0.0,        # base orientation
          -0.0, 0.72, -1.44,
           0.0, 0.72, -1.44,
          -0.0, 0.72, -1.44,
           0.0, 0.72, -1.44]

v_init : [0, 0, 0,
          0, 0, 0, 
          0, 0, 0,
          0, 0, 0,
          0, 0, 0,
          0, 0, 0]

# Cost Weights
Qq : [50, 50, 20, 
      20, 20, 20,
      5, 1, 1,
      5, 1, 1,
      5, 1, 1,
      5, 1, 1]

Qv : [1, 1, 1,
      1, 1, 1, 
      0.1, 0.05, 0.025,
      0.1, 0.05, 0.025,
      0.1, 0.05, 0.025,
      0.1, 0.05, 0.025]

R : [10000, 10000, 10000,
     10000, 10000, 10000, 
     0.001, 0.0005, 0.001,
     0.001, 0.0005, 0.001,
     0.001, 0.0005, 0.001,
     0.001, 0.0005, 0.001]

Qfq : [50, 50, 20, 
      20, 20, 20,
      5, 1, 1,
      5, 1, 1,
      5, 1, 1,
      5, 1, 1]

Qfv : [1, 1, 1,
      1, 1, 1, 
      0.1, 0.1, 0.1,
      0.1, 0.1, 0.1,
      0.1, 0.1, 0.1,
      0.1, 0.1, 0.1]

# Solver parameters
method : 1    # solver method, {linesearch, trust_region}
scaling : true
equality_constraints : false
linear_solver : 1 # linear solver method, {kDenseLdlt, kPentaDiagonalLu}
num_threads : 4

# Convergence thresholds
tolerances:
  rel_cost_reduction: 0
  abs_cost_reduction: 0
  rel_gradient_along_dq: 0
  abs_gradient_along_dq: 0
  rel_state_change: 0
  abs_state_change: 0

# Method used to compute gradients of inverse dynamics, one of
gradients_method: 0    # {forward_differences, central_differences, central_differences4, autodiff}

# Contact model parameters. 
contact_stiffness : 2000    # normal force stiffness, in N/m
dissipation_velocity : 0.1  # Hunt & Crossley-like model parameter, in m/s.

# Amount of smoothing (and therefore force at a distance) to apply when
# computing normal forces. This is equivalent to an analytical version of
# randomized smoothing, assuming that signed distances are drawn from a logistic
# distirbution with the smoothing factor as the scale parameter. Higher values
# mean more smoothing and more force at a distance. 
smoothing_factor : 0.01

# Friction
friction_coefficient : 1.0  # Coefficient of friction.
stiction_velocity: 0.5      # Regularization velocity, in m/s.

#gait heuristic
gaitHeuristic: 3  # 0 for trotting, 1 for bounding, 2 for pacing, 3 for free
# Symmetric Control Cost
symmetricControlCostCoefficient: 0.01

k_spring : 1000
d_damper : 2000
damper_smooth : 200
spring_smooth : 100
zOffset : -0.02

which_contact_model : 1  # 0 = soft; 1 = spring-damper(0 behaves better at moving, 1 is better at angular actions).

# foot slip and clearance cost
recompileFootSlipAndClearanceCost: false
cf: 1.0e+3
c1: -30

demo_vel_x: 0.3

# mpc settings
dt: 0.02
horizon: 50
mpcFrequency: 60
mrtFrequency: 500
useFeedbackPolicy: true

mpc_iters : 1
Kp : [20, 20, 20,
      20, 20, 20,
      20, 20, 20,
      20, 20, 20]
Kd : [2, 2, 2,
      2, 2, 2,
      2, 2, 2,
      2, 2, 2]

# estimate
use_cheater_mode              :  true
footRadius                    :  0.02
estimatorFrequency            :  500
foot_height_sensor_noise      :  0.001
foot_process_noise_position   :  0.002
foot_sensor_noise_position    :  0.001
foot_sensor_noise_velocity    :  0.1
imu_process_noise_position    :  0.02
imu_process_noise_velocity    :  0.02
